### ISSUE TITLE
meta canvas on/off issues

### ISSUE THREAD

**Issue by jameshadfield** [jameshadfield/JScandy#32]
- [ ] When the metacanvas is turned off then on it doesn't come back despite the canvas being re-created and the constituent component staying alive (i.e. ctx is maintained) and the render command being run... it's probably something to do with the (old) component not being linked to the new canvas. Maybe we should destroy everything then start a new instance?

- [ ] Upon loading with no metadata the canvas is rendered (i.e. takes up space) and the settings panel is locked to the "on" position

**Comment by simonrharris** [comment]
Related to this, turning individual metadata columns on or off resurrects the metacanvas, but the tree overlaps woth it. Turning off the metacanvas also stretches the gubbins/Roary canvas so text is stretched and becomes blurry.

**Comment by jameshadfield** [comment]
fixed in redux version
