### ISSUE TITLE
Plot GWAS data

### ISSUE THREAD

**Issue by johnlees** [jameshadfield/JScandy#42]
Like this: http://locuszoom.sph.umich.edu/locuszoom/
http://i1.rgstatic.net/figure/250924167_fig3_GWAS-of-plasma-CFH-and-CFHR1-concentrations-in-the-Croatian-cohort-(n--1004)-including/ddt33603

Input would be rows of variants, with columns with position on genome, p-val (or could be -log_10 p-val, which is what should be plotted) and optionally r^2 value which points are coloured by. If easy, point size could be proportional to effect size

**Comment by jameshadfield** [comment]
added in commit 323814b
